// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruyenVNAPI.Model;

#nullable disable

namespace TruyenVN.Migrations
{
    [DbContext(typeof(TruyenVNDbContext))]
    [Migration("20230724151606_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TruyenVN.StoryCategory", b =>
                {
                    b.Property<int>("cate_id")
                        .HasColumnType("int");

                    b.Property<int>("story_id")
                        .HasColumnType("int");

                    b.HasKey("cate_id", "story_id");

                    b.HasIndex("story_id");

                    b.ToTable("StoryCategories");

                    b.HasData(
                        new
                        {
                            cate_id = 1,
                            story_id = 1
                        },
                        new
                        {
                            cate_id = 2,
                            story_id = 1
                        },
                        new
                        {
                            cate_id = 3,
                            story_id = 1
                        },
                        new
                        {
                            cate_id = 5,
                            story_id = 1
                        },
                        new
                        {
                            cate_id = 1,
                            story_id = 2
                        },
                        new
                        {
                            cate_id = 2,
                            story_id = 2
                        },
                        new
                        {
                            cate_id = 4,
                            story_id = 2
                        },
                        new
                        {
                            cate_id = 1,
                            story_id = 3
                        },
                        new
                        {
                            cate_id = 3,
                            story_id = 3
                        },
                        new
                        {
                            cate_id = 6,
                            story_id = 3
                        },
                        new
                        {
                            cate_id = 2,
                            story_id = 3
                        },
                        new
                        {
                            cate_id = 2,
                            story_id = 4
                        },
                        new
                        {
                            cate_id = 3,
                            story_id = 4
                        },
                        new
                        {
                            cate_id = 1,
                            story_id = 4
                        },
                        new
                        {
                            cate_id = 5,
                            story_id = 4
                        },
                        new
                        {
                            cate_id = 1,
                            story_id = 5
                        },
                        new
                        {
                            cate_id = 3,
                            story_id = 5
                        },
                        new
                        {
                            cate_id = 5,
                            story_id = 5
                        },
                        new
                        {
                            cate_id = 1,
                            story_id = 6
                        },
                        new
                        {
                            cate_id = 3,
                            story_id = 6
                        },
                        new
                        {
                            cate_id = 2,
                            story_id = 6
                        },
                        new
                        {
                            cate_id = 9,
                            story_id = 6
                        },
                        new
                        {
                            cate_id = 1,
                            story_id = 7
                        },
                        new
                        {
                            cate_id = 3,
                            story_id = 7
                        },
                        new
                        {
                            cate_id = 5,
                            story_id = 7
                        },
                        new
                        {
                            cate_id = 1,
                            story_id = 8
                        },
                        new
                        {
                            cate_id = 3,
                            story_id = 8
                        },
                        new
                        {
                            cate_id = 5,
                            story_id = 8
                        },
                        new
                        {
                            cate_id = 9,
                            story_id = 8
                        },
                        new
                        {
                            cate_id = 5,
                            story_id = 9
                        },
                        new
                        {
                            cate_id = 4,
                            story_id = 9
                        },
                        new
                        {
                            cate_id = 11,
                            story_id = 9
                        },
                        new
                        {
                            cate_id = 11,
                            story_id = 10
                        },
                        new
                        {
                            cate_id = 10,
                            story_id = 10
                        },
                        new
                        {
                            cate_id = 7,
                            story_id = 10
                        },
                        new
                        {
                            cate_id = 7,
                            story_id = 11
                        },
                        new
                        {
                            cate_id = 10,
                            story_id = 11
                        },
                        new
                        {
                            cate_id = 5,
                            story_id = 11
                        },
                        new
                        {
                            cate_id = 9,
                            story_id = 12
                        },
                        new
                        {
                            cate_id = 10,
                            story_id = 12
                        },
                        new
                        {
                            cate_id = 11,
                            story_id = 12
                        },
                        new
                        {
                            cate_id = 5,
                            story_id = 13
                        },
                        new
                        {
                            cate_id = 4,
                            story_id = 13
                        },
                        new
                        {
                            cate_id = 7,
                            story_id = 13
                        },
                        new
                        {
                            cate_id = 1,
                            story_id = 14
                        },
                        new
                        {
                            cate_id = 2,
                            story_id = 14
                        },
                        new
                        {
                            cate_id = 3,
                            story_id = 14
                        },
                        new
                        {
                            cate_id = 2,
                            story_id = 15
                        },
                        new
                        {
                            cate_id = 3,
                            story_id = 15
                        },
                        new
                        {
                            cate_id = 6,
                            story_id = 15
                        },
                        new
                        {
                            cate_id = 2,
                            story_id = 16
                        },
                        new
                        {
                            cate_id = 3,
                            story_id = 16
                        },
                        new
                        {
                            cate_id = 6,
                            story_id = 16
                        },
                        new
                        {
                            cate_id = 9,
                            story_id = 17
                        },
                        new
                        {
                            cate_id = 10,
                            story_id = 17
                        },
                        new
                        {
                            cate_id = 11,
                            story_id = 17
                        },
                        new
                        {
                            cate_id = 4,
                            story_id = 18
                        },
                        new
                        {
                            cate_id = 8,
                            story_id = 18
                        },
                        new
                        {
                            cate_id = 10,
                            story_id = 18
                        },
                        new
                        {
                            cate_id = 11,
                            story_id = 18
                        },
                        new
                        {
                            cate_id = 7,
                            story_id = 19
                        },
                        new
                        {
                            cate_id = 10,
                            story_id = 19
                        },
                        new
                        {
                            cate_id = 11,
                            story_id = 19
                        },
                        new
                        {
                            cate_id = 3,
                            story_id = 20
                        },
                        new
                        {
                            cate_id = 4,
                            story_id = 20
                        },
                        new
                        {
                            cate_id = 5,
                            story_id = 20
                        });
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Author", b =>
                {
                    b.Property<int>("author_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("author_id"), 1L, 1);

                    b.Property<string>("author_description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("author_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("author_id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            author_id = 1,
                            author_description = "Mashima Hiro là một họa sĩ manga người Nhật nổi tiếng với ba bộ truyện Rave Master, Fairy Tail và Edens Zero.",
                            author_name = "Mashima Hiro"
                        },
                        new
                        {
                            author_id = 2,
                            author_description = "Kishimoto Masashi là một họa sĩ truyện tranh đã được biết đến qua bộ truyện tranh nổi tiếng thế giới Naruto",
                            author_name = "Kishimoto Masashi"
                        },
                        new
                        {
                            author_id = 3,
                            author_description = "Oda Eiichirō là một họa sĩ truyện tranh người Nhật Bản, hiện đang sáng tác cho nhà xuất bản Shūeisha",
                            author_name = "Oda Eiichiro"
                        },
                        new
                        {
                            author_id = 4,
                            author_description = "Atsuo Ueda là trợ lí cho họa sĩ Mashima Hiro",
                            author_name = "Atsuo Ueda"
                        },
                        new
                        {
                            author_id = 5,
                            author_description = "Fujiko Fujio là bút danh chung của hai nghệ sĩ manga Nhật Bản, người Việt gọi là Ông Hai Phú hay Ông Phú Sĩ.",
                            author_name = "Fujiko Fujio"
                        },
                        new
                        {
                            author_id = 6,
                            author_description = "Trương Uy, là một tiểu thuyết gia, văn học mạng người Trung Quốc, được biết đến với bút danh Đường Gia Tam Thiếu.",
                            author_name = "Đường Gia Tam Thiếu"
                        },
                        new
                        {
                            author_id = 7,
                            author_description = "Chưa có thông tin",
                            author_name = "Umemura Shinya"
                        },
                        new
                        {
                            author_id = 8,
                            author_description = "Ông là một mangaka nổi tiếng với các tác phẩm như Yaiba, Magic Kaito hay Thám tử lừng danh Conan.",
                            author_name = "Aoyama Gōshō"
                        },
                        new
                        {
                            author_id = 9,
                            author_description = "Anh bắt đầu viết tiểu thuyết khi còn mới là học sinh trung học và dần trở thành một trong những cây bút tiêu biểu của văn học mạng Trung Quốc",
                            author_name = "Thiên Tằm Thổ Đậu"
                        },
                        new
                        {
                            author_id = 10,
                            author_description = "Đang cập nhật",
                            author_name = "Đang cập nhật"
                        });
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Category", b =>
                {
                    b.Property<int>("cate_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cate_id"), 1L, 1);

                    b.Property<string>("cate_description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("cate_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("cate_id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            cate_id = 1,
                            cate_description = "Nội dung của những bộ manga này thường liên quan đến đánh nhau và/hoặc bạo lực (ở mức bình thường, không thái quá)",
                            cate_name = "Shounen"
                        },
                        new
                        {
                            cate_id = 2,
                            cate_description = "Thể loại xuất phát từ trí tưởng tượng phong phú, từ pháp thuật đến thế giới trong mơ thậm chí là những câu chuyện thần tiên",
                            cate_name = "Fantasy"
                        },
                        new
                        {
                            cate_id = 3,
                            cate_description = "Thể loại phiêu lưu, mạo hiểm, thường là hành trình của các nhân vật",
                            cate_name = "Adventure"
                        },
                        new
                        {
                            cate_id = 4,
                            cate_description = "Thể loại mang đến cho người xem những cảm xúc khác nhau: buồn bã, căng thẳng thậm chí là bi phẫn",
                            cate_name = "Drama"
                        },
                        new
                        {
                            cate_id = 5,
                            cate_description = "Thể loại có nội dung trong sáng và cảm động, thường có các tình tiết gây cười, các xung đột nhẹ nhàng",
                            cate_name = "Comedy"
                        },
                        new
                        {
                            cate_id = 6,
                            cate_description = "Thể loại này thường có nội dung về đánh nhau, bạo lực, hỗn loạn, với diễn biến nhanh",
                            cate_name = "Action"
                        },
                        new
                        {
                            cate_id = 7,
                            cate_description = "Thường là những câu chuyện về tình yêu, tình cảm lãng mạn.",
                            cate_name = "Romance"
                        },
                        new
                        {
                            cate_id = 8,
                            cate_description = "Thể loại này là những câu chuyện về người ở một thế giới này xuyên đến một thế giới khác",
                            cate_name = "Chuyển Sinh"
                        },
                        new
                        {
                            cate_id = 9,
                            cate_description = "Truyện tranh của Trung Quốc",
                            cate_name = "Manhua"
                        },
                        new
                        {
                            cate_id = 10,
                            cate_description = "Truyện thuộc kiểu lãng mạn, kể về những sự kiện vui buồn trong tình yêu của nhân vật chính.",
                            cate_name = "Ngôn Tình"
                        },
                        new
                        {
                            cate_id = 11,
                            cate_description = "Nội dung của những bộ manga này thường liên quan đến tình cảm lãng mạn, chú trọng đầu tư cho nhân vật (tính cách,...)",
                            cate_name = "Shoujo"
                        });
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Chapter", b =>
                {
                    b.Property<int>("chapter_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("chapter_id"), 1L, 1);

                    b.Property<int>("chapter_number")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("story_id")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("chapter_id");

                    b.HasIndex("story_id");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            chapter_id = 1,
                            chapter_number = 1,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688894100/Fairy%20Tail/chapter1_itasyx.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8469),
                            story_id = 1,
                            title = "Chapter 1",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8469)
                        },
                        new
                        {
                            chapter_id = 2,
                            chapter_number = 2,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688894100/Fairy%20Tail/chapter2.1_itasyx.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8471),
                            story_id = 1,
                            title = "Chapter 2.1",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8472)
                        },
                        new
                        {
                            chapter_id = 3,
                            chapter_number = 3,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688894100/Fairy%20Tail/chapter2.2_itasyx.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8473),
                            story_id = 1,
                            title = "Chapter 2.2",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8473)
                        },
                        new
                        {
                            chapter_id = 4,
                            chapter_number = 4,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688894100/Fairy%20Tail/chapter3.1_itasyx.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8474),
                            story_id = 1,
                            title = "Chapter 3.1",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8475)
                        },
                        new
                        {
                            chapter_id = 5,
                            chapter_number = 5,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688894100/Fairy%20Tail/chapter3.2_itasyx.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8475),
                            story_id = 1,
                            title = "Chapter 3.2",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8476)
                        },
                        new
                        {
                            chapter_id = 6,
                            chapter_number = 1,
                            content = "Error",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8477),
                            story_id = 2,
                            title = "",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8477)
                        },
                        new
                        {
                            chapter_id = 7,
                            chapter_number = 2,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688895954/Naruto/chapter2.1_c5wrar.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8479),
                            story_id = 2,
                            title = "Konohamaru",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8479)
                        },
                        new
                        {
                            chapter_id = 8,
                            chapter_number = 3,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688895954/Naruto/chapter2.2_c5wrar.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8481),
                            story_id = 2,
                            title = "Konohamaru-next",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8481)
                        },
                        new
                        {
                            chapter_id = 9,
                            chapter_number = 4,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688895954/Naruto/chapter3.1_c5wrar.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8482),
                            story_id = 2,
                            title = "Uchiha Sasuke",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8482)
                        },
                        new
                        {
                            chapter_id = 10,
                            chapter_number = 5,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688895954/Naruto/chapter3.2_c5wrar.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8483),
                            story_id = 2,
                            title = "Uchiha Sasuke-next",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8484)
                        },
                        new
                        {
                            chapter_id = 11,
                            chapter_number = 1,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688896729/One%20Piece/chapter1.1_qjkjcz.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8484),
                            story_id = 3,
                            title = "Bắt đầu chuyến hành trình",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8485)
                        },
                        new
                        {
                            chapter_id = 12,
                            chapter_number = 2,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688896729/One%20Piece/chapter1.2_qjkjcz.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8486),
                            story_id = 3,
                            title = "Bắt đầu chuyến hành trình - next",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8486)
                        },
                        new
                        {
                            chapter_id = 13,
                            chapter_number = 3,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688896729/One%20Piece/chapter1.3_qjkjcz.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8487),
                            story_id = 3,
                            title = "Bắt đầu chuyến hành trình - next",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8487)
                        },
                        new
                        {
                            chapter_id = 14,
                            chapter_number = 4,
                            content = "Error",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8488),
                            story_id = 3,
                            title = "Chapter",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8489)
                        },
                        new
                        {
                            chapter_id = 15,
                            chapter_number = 5,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688897211/One%20Piece/chapter3.1_klvvkc.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8490),
                            story_id = 3,
                            title = "Thợ săn hải tặc zoro",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8490)
                        },
                        new
                        {
                            chapter_id = 16,
                            chapter_number = 6,
                            content = "https://res.cloudinary.com/dhboy15q8/image/upload/v1688897211/One%20Piece/chapter3.2_klvvkc.jpg",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8491),
                            story_id = 3,
                            title = "Thợ săn hải tặc zoro - next",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8491)
                        },
                        new
                        {
                            chapter_id = 17,
                            chapter_number = 1,
                            content = "https://res.cloudinary.com/dhboy15q8/raw/upload/v1688897810/%C4%90%C3%A2%CC%81u%20Pha%CC%81%20Th%C6%B0%C6%A1ng%20Khung/chapter1_lpk36g.json",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8492),
                            story_id = 8,
                            title = "Thiên tài rơi rụng",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8492)
                        },
                        new
                        {
                            chapter_id = 18,
                            chapter_number = 2,
                            content = "https://res.cloudinary.com/dhboy15q8/raw/upload/v1688897951/%C4%90%C3%A2%CC%81u%20Pha%CC%81%20Th%C6%B0%C6%A1ng%20Khung/chapter2_rd9jwr.json",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8494),
                            story_id = 8,
                            title = "Đấu khí đại lục",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8494)
                        },
                        new
                        {
                            chapter_id = 19,
                            chapter_number = 3,
                            content = "https://res.cloudinary.com/dhboy15q8/raw/upload/v1688897951/%C4%90%C3%A2%CC%81u%20Pha%CC%81%20Th%C6%B0%C6%A1ng%20Khung/chapter3_rd9jwr.json",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8495),
                            story_id = 8,
                            title = "Khách nhân",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8495)
                        },
                        new
                        {
                            chapter_id = 20,
                            chapter_number = 4,
                            content = "https://res.cloudinary.com/dhboy15q8/raw/upload/v1688897951/%C4%90%C3%A2%CC%81u%20Pha%CC%81%20Th%C6%B0%C6%A1ng%20Khung/chapter4_rd9jwr.json",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8496),
                            story_id = 8,
                            title = "Vân Lam tông",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8497)
                        },
                        new
                        {
                            chapter_id = 21,
                            chapter_number = 5,
                            content = "https://res.cloudinary.com/dhboy15q8/raw/upload/v1688897951/%C4%90%C3%A2%CC%81u%20Pha%CC%81%20Th%C6%B0%C6%A1ng%20Khung/chapter5_rd9jwr.json",
                            create_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8497),
                            story_id = 8,
                            title = "Tụ Khí Tán",
                            update_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8498)
                        });
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("chapter_id")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("send_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("chapter_id");

                    b.HasIndex("user_id");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            chapter_id = 1,
                            message = "OK",
                            send_at = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8446),
                            user_id = 1
                        });
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Story", b =>
                {
                    b.Property<int>("story_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("story_id"), 1L, 1);

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.Property<int>("author_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<bool>("isComic")
                        .HasColumnType("bit");

                    b.Property<string>("story_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("story_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.HasKey("story_id");

                    b.HasIndex("author_id");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            story_id = 1,
                            View = 50,
                            author_id = 1,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Xuyên suốt câu chuyện là cuộc phiêu lưu của một Sorceress tên là Lucy Heartphilia, sau khi cô tham gia vào hiệp hội hội Fairy Tail, cô đã cùng với Natsu Dragneel hành trình để đi tìm một con rồng tên là Igneel.",
                            isComic = true,
                            story_image = "https://news-w.com/wp-content/uploads/2022/03/ve-hoi-phap-su-thumbnail.jpg",
                            story_name = "Hội pháp sư - Fairy Tail",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 2,
                            View = 30,
                            author_id = 2,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Câu chuyện xoay quanh Uzumaki Naruto, một ninja trẻ muốn tìm cách khẳng định mình để được mọi người công nhận và nuôi ước mơ trở thành Hokage - người lãnh đạo Làng Lá. ",
                            isComic = true,
                            story_image = "https://upload.wikimedia.org/wikipedia/en/9/94/NarutoCoverTankobon1.jpg",
                            story_name = "Naruto",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 3,
                            View = 28,
                            author_id = 3,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = ". One Piece kể về cuộc hành trình của Monkey D. Luffy - thuyền trưởng của băng hải tặc Mũ Rơm và các đồng đội của cậu. Luffy tìm kiếm vùng biển bí ẩn nơi cất giữ kho báu lớn nhất thế giới One Piece, với mục tiêu trở thành Vua Hải Tặc.",
                            isComic = true,
                            story_image = "https://i.truyenvua.com/slider/290x191/slider_1559211185.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Đảo Hải Tặc - One Piece",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 4,
                            View = 0,
                            author_id = 4,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Phần tiếp theo của loạt truyện đình đám cùng tên khi nhóm Natsu đi làm nhiệm vụ trăm năm",
                            isComic = true,
                            story_image = "https://i.truyenvua.com/slider/290x191/slider_1561609693.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Fairy Tail - Nhiệm vụ trăm năm",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 5,
                            View = 12,
                            author_id = 5,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Trong truyện lấy bối cảnh ở thế kỷ 22, Doraemon là chú mèo robot của tương lai do xưởng Matsushiba — công xưởng chuyên sản xuất robot vốn dĩ nhằm mục đích chăm sóc trẻ nhỏ.",
                            isComic = true,
                            story_image = "https://vcdn.tikicdn.com/cache/450x450//media/catalog/product/i/m/img225_11.jpg",
                            story_name = "Doraemon",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 6,
                            View = 0,
                            author_id = 6,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "câu chuyện về Đường Tam, một thiên tài chế tạo ám khí của đường môn đã xuyên không đến Đấu La Đại Lục.",
                            isComic = false,
                            story_image = "https://hhhkungfu.tv/wp-content/uploads/Dau-La-Dai-Luc-2.jpg",
                            story_name = "Đấu la đại lục",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 7,
                            View = 0,
                            author_id = 7,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Truyện xoay quanh một cậu thám tử trung học có tên là Kudo Shinichi trong lúc đang điều tra một Tổ chức Áo đen bí ẩn đã bị ép phải uống một loại thuốc độc có thể gây chết người. May mắn là cậu đã sống sót nhưng cơ thể thì lại bị teo nhỏ như một đứa bé 6 tuổi. Kể từ đó để tránh bị lộ thân phận thực sự của mình, cậu đã lấy tên là Edogawa Conan và chuyển đến sống ở nhà của cô bạn thời thơ ấu Mori Ran cùng với bố của cô ấy là một thám tử tư tên Mori Kogoro với hy vọng một ngày nào đó cậu có thể hạ gục Tổ chức Áo Đen và lấy lại hình dáng ban đầu.",
                            isComic = true,
                            story_image = "https://im.uniqlo.com/global-cms/spa/rese7e57a44a646f56f9cf35532a9777337fr.jpg",
                            story_name = "Conan",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 8,
                            View = 0,
                            author_id = 8,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Đấu Phá Thương Khung là một câu chuyện huyền huyễn đặc sắc kể về Tiêu Viêm, một thiên chi kiêu tử với thiên phú tu luyện mà ai ai cũng hâm mộ, bỗng một ngày người mẹ mất đi đễ lại di vật là một chiếc giới chỉ màu đen nhưng từ khi đó Tiêu Viêm đã mất đi thiên phú tu luyện của mình.\r\n\r\n- Từ thiên tài rớt xuống làm phế vật trong 3 năm, rồi bị vị hôn thê thẳng thừng từ hôn, làm dấy lên ý chí nam nhi của mình, Tiêu Viêm nhờ di vật của mẫu thân để lại là 1 chiếc hắc giới chỉ (nhẫn màu đen)Tiêu Viêm gặp được hồn của Dược Lão (Dược Trần – Dược tôn giả) 1 đại luyện dược tông sư của đấu khí đại lục…",
                            isComic = false,
                            story_image = "https://img.meta.com.vn/Data/image/2021/11/01/lich-chieu-dau-pha-khung-thuong-ova-3.jpg",
                            story_name = "Đấu phá thương khung",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 9,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "“Hãy chia tay với tên khốn đó đi”\r\nCái gì? Cậu là bạn của tôi đó…!\r\n“Sang Jae Soo” người muốn tôi và người yêu chia tay. Và tôi, người không thể đẩy cậu ấy ra xa, ‘Ha Won Soo.",
                            isComic = true,
                            story_image = "https://i.truyenvua.com/ebook/190x247/that-dang-thuong-cho-chung-toi_1688092650.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Thật Đáng Thương Cho Chúng Tôi",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 10,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Nhan Xu một thời xuyên qua trên người nữ phụ độc ác của tiểu thuyết nam tần, nữ phụ ác độc từ trước đến nay đối với nam chính Tiêu Tịch Hàn chuyện xấu nào cũng làm, để tránh cho kết cục bi thảm, Nhan Xu quyết định dùng tình yêu của mẹ già làm ấm lòng Tiêu Tịch Hàn lạnh như băng",
                            isComic = true,
                            story_image = "https://truyenvua.com/14393/1/1.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Mở Đầu Ta Ngược Đãi Nam Chủ",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 11,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Câu chuyện về một cuộc hôn nhân không tình yêu ở một tiệm cá vàng. Còn bao chap sẽ yêu nhau thì không biết. Mong không có nhiều drama",
                            isComic = true,
                            story_image = "https://i.truyenvua.com/ebook/190x247/cap-vo-chong-ho-o-tiem-ca-vang_1687656150.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Cặp Vợ Chồng Hờ Ở Tiệm Cá Vàng",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 12,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Takuro Sakamoto là một kẻ thất bại 30 tuổi vẫn sống với bố mẹ. Chán ngấy với công việc bế tắc và cuộc sống nói chung, anh bị một người bạn thuyết phục chơi thử trò chơi thực tế ảo. Nhưng ngay cả đối tác ảo của anh ấy là Tsukiko hay đơn giản là “Nguyệt” cũng rối rắm hơn gã tưởng.",
                            isComic = true,
                            story_image = "https://i.truyenvua.com/ebook/190x247/ressentiment_1688627279.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Ressentiment",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 13,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Một ngôi trường toàn wibu - wibu muôn năm",
                            isComic = true,
                            story_image = "",
                            story_name = "Trường Học Wibu",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 14,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Aster và Yuno là hai đứa trẻ bị bỏ rơi ở nhà thờ và cùng nhau lớn lên tại đó. Khi còn nhỏ, chúng đã hứa với nhau xem ai sẽ trở thành Ma pháp vương tiếp theo. Thế nhưng, khi cả hai lớn lên, mọi sô chuyện đã thay đổi. Yuno là thiên tài ma pháp với sức mạnh tuyệt đỉnh trong khi Aster lại không thể sử dụng ma pháp và cố gắng bù đắp bằng thể lực",
                            isComic = true,
                            story_image = "https://i.truyenvua.com/slider/290x191/slider_1560493497.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Black Clover - Thế Giới Phép Thuật",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 15,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Kimetsu no Yaiba – Tanjirou là con cả của gia đình vừa mất cha. Một ngày nọ, Tanjirou đến thăm thị trấn khác để bán than, khi đêm về cậu ở nghỉ tại nhà người khác thay vì về nhà vì lời đồn thổi về ác quỷ luôn rình mò gần núi vào buổi tối. Khi cậu về nhà vào ngày hôm sau, bị kịch đang đợi chờ cậu…",
                            isComic = true,
                            story_image = "https://image.api.playstation.com/vulcan/ap/rnd/202106/1704/2ZfAUG5CTXdM34S1OhmMW1zF.jpg",
                            story_name = "Thanh Gươm Diệt Quỷ",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 16,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Thất đại ác nhân, một nhóm chiến binh có tham vọng lật đổ vương quốc Britannia, được cho là đã bị tiêu diệt bởi các “hiệp sĩ thánh chiến” mặc dù vẫn còn 1 số người cho rằng họ vẫn còn sống. 10 năm sau, Các hiệp sĩ thánh chiến đã làm 1 cuộc đảo chính và khống chế đức vua, họ trở thành người cai trị độc tài mới của vương quốc",
                            isComic = true,
                            story_image = "https://i.truyenvua.com/slider/290x191/slider_1559213426.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Thất Hình Đại Tội",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 17,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Truyện tranh Va Phải Đại Boss được cập nhật nhanh và đầy đủ nhất tại TruyenVN",
                            isComic = false,
                            story_image = "https://i.truyenvua.com/ebook/190x247/va-phai-dai-boss_1686616982.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Va Phải Đại Boss",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 18,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Đích nữ Bán Hạ bị chị kế và Thái tử ca ca mưu hại đến chết. Sau khi tỉnh lại, nàng trọng sinh đến thời điểm trước khi trở về kinh đô. Mang theo ký ức của kiếp trước, nàng đã lột bỏ làn da đẹp đẽ của người chị kế độc ác, và vạch trần bộ mặt bồ tát giả tạo của người mẹ kế đạo đức giả",
                            isComic = true,
                            story_image = "https://i.truyenvua.com/ebook/190x247/ke-hoach-tra-thu-cua-dich-nu-trong-sinh_1686616863.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Kế Hoạch Trả Thù Của Đích Nữ Trọng Sinh",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 19,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Con sói dễ thương và đáng yêu, bị cô bé quàng khăn đỏ ăn thịt...!?\r\nSói Luka vốn định uy hiếp cô bé quàng khăn đỏ, nhưng chẳng biết vì sao lại bị cho rằng đang tỏ tình và bị ăn thịt.Luka luôn bị tấn công thế này, nhưng khi đêm trăng tròn thì...?",
                            isComic = false,
                            story_image = "https://i.truyenvua.com/ebook/190x247/co-be-quang-khan-do-thit-soi_1686808465.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Cô Bé Quàng Khăn Đỏ Thịt Sói",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            story_id = 20,
                            View = 0,
                            author_id = 10,
                            create_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            description = "Câu truyện trước và sau của bộ phim \"King The Land\".\r\nNụ cười của thiên thần rạng rỡ nhất trần đời đã cứu rỗi lấy vị hoàng tử chúa ghét tiếng cười. Truyện kể về lần đầu tiên hai người gặp nhau và những câu chuyện thời thơ ấu.",
                            isComic = false,
                            story_image = "https://i.truyenvua.com/ebook/190x247/vung-dat-rong-lon_1687076282.jpg?gt=hdfgdfg&mobile=2",
                            story_name = "Vùng Đất Rộng Lớn",
                            update_at = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("TruyenVNAPI.Model.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"), 1L, 1);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("user_id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            user_id = 1,
                            CreateAt = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8353),
                            DateOfBirth = "12/12/2001",
                            Email = "user@gmail.com",
                            Gender = "Male",
                            Name = "user",
                            Password = "123",
                            Role = 0,
                            isActive = true
                        },
                        new
                        {
                            user_id = 2,
                            CreateAt = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8355),
                            DateOfBirth = "22/07/2001",
                            Email = "admin@TruyenVn.com",
                            Gender = "Female",
                            Name = "admin",
                            Password = "123",
                            Role = 1,
                            isActive = true
                        });
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Viewed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("chapter_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_view")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("chapter_id");

                    b.HasIndex("user_id");

                    b.ToTable("Vieweds");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            chapter_id = 2,
                            date_view = new DateTime(2023, 7, 24, 22, 16, 6, 566, DateTimeKind.Local).AddTicks(8457),
                            user_id = 2
                        });
                });

            modelBuilder.Entity("TruyenVN.StoryCategory", b =>
                {
                    b.HasOne("TruyenVNAPI.Model.Category", "Category")
                        .WithMany("StoryCategories")
                        .HasForeignKey("cate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenVNAPI.Model.Story", "Story")
                        .WithMany("StoryCategories")
                        .HasForeignKey("story_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Chapter", b =>
                {
                    b.HasOne("TruyenVNAPI.Model.Story", "Stories")
                        .WithMany("Chapters")
                        .HasForeignKey("story_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Report", b =>
                {
                    b.HasOne("TruyenVNAPI.Model.Chapter", "Chapters")
                        .WithMany()
                        .HasForeignKey("chapter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenVNAPI.Model.User", "Users")
                        .WithMany("Reports")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapters");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Story", b =>
                {
                    b.HasOne("TruyenVNAPI.Model.Author", "Authors")
                        .WithMany("Stories")
                        .HasForeignKey("author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authors");
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Viewed", b =>
                {
                    b.HasOne("TruyenVNAPI.Model.Chapter", "Chapters")
                        .WithMany("Vieweds")
                        .HasForeignKey("chapter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenVNAPI.Model.User", "Users")
                        .WithMany("Vieweds")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapters");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Author", b =>
                {
                    b.Navigation("Stories");
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Category", b =>
                {
                    b.Navigation("StoryCategories");
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Chapter", b =>
                {
                    b.Navigation("Vieweds");
                });

            modelBuilder.Entity("TruyenVNAPI.Model.Story", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("StoryCategories");
                });

            modelBuilder.Entity("TruyenVNAPI.Model.User", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Vieweds");
                });
#pragma warning restore 612, 618
        }
    }
}
